service: docker
language: elixir
elixir:
  - 1.6
before_script:
  - sudo useradd -u 5000 tb0
  - sudo useradd -u 5001 tb1
  - sudo useradd -u 5002 tb2
  - sudo tar xvf test/test_data.tar
script:
  - sudo /bin/bash -c ". test/mix_environment; mix test"
# the awk removes:
# * "total" lines - which vary between file system types
# * sizes from directories - which vary between filesystem types
# * GNU "extra permissions" indicator (. or +) at the end of the mode line
# * the date, which tends to change ;-)
  - sudo ls -lR test/dir | awk '/^total / { next } /^d/ { $5="" } { gsub(/[.+]/,"",$1);$6=""; $7=""; $8=""; print }' | diff -b -u test/after -

