service: docker
language: elixir
elixir:
  - 1.6
before_script:
  - sudo useradd -u 5000 tb0
  - sudo useradd -u 5001 tb1
  - sudo tar xvf test/test_data.tar
script:
  - env
#  - sudo /bin/sh -c "setup environment; mix test"
#  - sudo ls -lR test/dir | diff -u test/after -

